---

- name: First playbook for new Ubuntu LVDI env
  connection: local
  gather_facts: false
  become: true
  hosts:
    - localhost
  become_method: sudo
  tasks:
    - name: "Install MY favourite packages"
      apt:
        pkg: "{{ item }}"
        state: present
      with_items:
          - glances
          - htop
          - hstr
          - gnome-tweaks